# WARNING: this file is not suitable for production, please use with caution
version: '3'

services:
  web:
    image: feedstar
    build: .
    command: gunicorn -b 0.0.0.0:5000 feedstar.wsgi:app
    env_file:
      - ./.flaskenv
    environment:
      - DATABASE_URI=sqlite:////db/feedstar.db
    volumes:
      - ./feedstar:/code/feedstar
      - ./db/:/db/
    ports:
      - "5000:5000"
