package main

import (
	"net/http"

	"github.com/helithumper/feed-star/api/db"
	_ "github.com/helithumper/feed-star/api/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/helithumper/feed-star/api/handler"
	"github.com/helithumper/feed-star/api/store"
	"github.com/labstack/echo/v4"
	"github.com/swaggo/echo-swagger"
)

// @title FeedStar API
// @version 1.0
// @description API Backing for the FeedStar News Aggregator

// @host localhost
// @BasePath /api
func main() {
	// Echo instance
	e := echo.New()

	// Middleware
	// e.Use(middleware.Logger())
	// e.Use(middleware.Recover())

	// HealthCheck godoc
	e.GET("/healthcheck", func(c echo.Context) error {
		return c.String(http.StatusOK, "okay")
	})

	v1 := e.Group("/api")

	d := db.New()
	db.AutoMigrate(d)

	as := store.NewArticleStore(d)
	h := handler.NewHandler(as)
	h.Register(v1)

	e.GET("/swagger/*", echoSwagger.WrapHandler)

	e.Logger.Fatal(e.Start(":1323"))

}
